### ISSUE TITLE
How does generating work?

### ISSUE THREAD

**Issue by Shpigford** [dburkes/acts_as_event_owner#10]
I see there's the ability to enable/disable event generation...how does that functionality work in terms of the future?

For instance, I created an event that repeats daily and it generated 30 events...what happens when those 30 events have occurred (ie. in a month)?

**Comment by dburkes** [comment]
When you create a new event_specification, 30 days worth of event_occurrences are generated by default.  You can change this default behavior by passing the :generate option when you create the event_occurrence.  See the "autogeneration" section of event_specification_spec.rb for examples.

For events outside of the autogeneration window, you'll need to generate them on-demand, or periodically (say, via cron), by calling events.generate on your container class (e.g.- my_user.events.generate), passing the same options as you can use for the :generate option in creation.  See some examples in core_spec.rb
