### ISSUE TITLE
undefined method `full_gem_path' for nil:NilClass

### ISSUE THREAD

**Issue by Shpigford** [dburkes/acts_as_event_owner#8]
I get the following error after adding that line to the Rakefile:

`undefined method`full_gem_path' for nil:NilClass`

I'm running Rails 2.3.4 for this app.

**Comment by Shpigford** [comment]
Ignore this, I'm an idiot.

**Comment by dburkes** [comment]
Uh, ok :-)

**Comment by yessinf** [comment]
Sorry, may i know what the root cause of this issue?
