### ISSUE TITLE
How do I differentiate event types?

### ISSUE THREAD

**Issue by Shpigford** [dburkes/acts_as_event_owner#9]
When creating an event, how do I differentiate what type of event it is (ie. Appointment, Medicine, Upkeep)?

**Comment by dburkes** [comment]
The generated migration defines the basic fields that the plugin needs- if you want to add fields to event specifications (and event occurrences), you should generate a new migration to add those columns.

Currently the value of those columns in event_specifications won't be carried over to event_occurrences- that's a bug and I'll document and fix that separately.
